spring.application.name=sneaker-drops-api-3
spring.datasource.url=jdbc:mysql://localhost:3306/sneakerdrops
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update